service: thumbnail-generator

provider:
  name: aws
  runtime: java11
  profile: rieckpil-github # make sure to create this profile or replace it with an existing
  region: eu-central-1
  timeout: 10
  memorySize: 1024
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:*'
      Resource:
        - 'arn:aws:s3:::${self:custom.thumbnailBucket}/*'
        - !Join ['', ['arn:aws:s3:::', !Ref ServerlessDeploymentBucket, '/*']]

custom:
  thumbnailBucket: image-uploads-java-thumbnail-example # S3 bucket names are unique

package:
  artifact: target/thumbnail-generator.jar

functions:
  thumbnailer:
    handler: de.rieckpil.blog.ThumbnailHandler
    events:
      - s3:
          bucket: ${self:custom.thumbnailBucket}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
    environment:
      THUMBNAIL_SIZE: 100
