version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew clean buildZip
      - sam package
        --template-file template.yml
        --output-template-file package.yml
        --s3-bucket demo-ci-cd-sam-bucket
artifacts:
  files:
    - package.yml
